// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function InstallDependency(arg1) {
  return window['go']['main']['App']['InstallDependency'](arg1);
}

export function OpenArtifact(arg1, arg2) {
  return window['go']['main']['App']['OpenArtifact'](arg1, arg2);
}

export function PickKeywordsFile() {
  return window['go']['main']['App']['PickKeywordsFile']();
}

export function PickOutputDirectory() {
  return window['go']['main']['App']['PickOutputDirectory']();
}

export function PickSourceDirectory() {
  return window['go']['main']['App']['PickSourceDirectory']();
}

export function PrescanSource(arg1) {
  return window['go']['main']['App']['PrescanSource'](arg1);
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function ValidateRun(arg1) {
  return window['go']['main']['App']['ValidateRun'](arg1);
}
